### ISSUE TITLE
Is this permitted by Rockstar?

### ISSUE THREAD

**Issue by ML-Song** [gjy3035/GCC-CL#1]

**Comment by gjy3035** [comment]
Rockstar Games allows the players to develop the mod for noncommercial or personal use. 
More detials: 
1. https://support.rockstargames.com/articles/115009494848/PC-Single-Player-Mods
2. https://support.rockstargames.com/articles/200153756/Policy-on-posting-copyrighted-Rockstar-Games-material

**Comment by ML-Song** [comment]
Thank you for your prompt reply.
