### ISSUE TITLE
How is pedInfo.xml file generated? What is the use of this file? Is the GCC labeler works if only a raw image is fed into the network?

### ISSUE THREAD

**Issue by 07Agarg** [gjy3035/GCC-CL#10]

**Comment by Elin24** [comment]
pefInfo.xml is generated by GCC-Collector. Relevant label information is saved in it.

GCC-Labeler leverages the information in pedInfo.xml to announce the crowd image. So it could not work with only a raw image file.

**Comment by 07Agarg** [comment]
Okay. Thanks
