### ISSUE TITLE
After Python scripts execute,  no Mask image output

### ISSUE THREAD

**Issue by 2811299** [gjy3035/GCC-CL#12]
After executing Python script without any error, only some normal GTA screenshot generated, but where's the mask picture?

I got output folders as:
jpgs
jsons
mats
pngs
vis

But I can't get images with people masked. I can get ```combination.bmp``` under gta data folder, I check source code, the ```result.jpg``` will be renamed and moved to the ```VIS``` folder, but still they're not mask image...

collected logs here [data.zip](https://github.com/gjy3035/GCC-CL/files/3567415/data.zip)

And I also find out my collected image folder struct like :
/data/part_1_0/1567414646/
part_0.raw
part_0_0.bmp
part_0_1.bmp
pedinfo.xml
only 4 files.

Why missing files about 180 and 360? Is it because something wrong with camera?

I extactly follow the instructions, except for installing the mod ```No Chromatic aberration & Lens distortion```, ```noVehicle```, ```unlimitedLife```

I really appreciate it if anyeone could reply anything.

**Comment by Elin24** [comment]
there should be 6 output folders after running GCC-Labeler:
> jpgs, jsons, mats, pngs, segs, vis

Mask pictures are saved in `segs/`. These *.raw files could be read by:
```
def getMask(rawfile):
    stencil = np.fromfile(rawfile, 'uint8')
    stencil = stencil.reshape(1080, 1920)
    stencil = np.where(np.isin(stencil, (1, 17)), 1, 0).astype('uint8')# OUTDOOR
    # stencil = np.where(np.isin(stencil, (9, 25)), 1, 0).astype('uint8')# INDOOR
    return stencil
```

Missing files about 180 and 360 is OK, it would be generated when the number of people is larger than 360. 

The quality of labels without these three mods would become worse. Because these pedestrians generated by GTA5 may not be labeled, and lens distortion would lead to mask with unmatched pixels.

**Comment by 2811299** [comment]
I'm really very sorry to bother you, could you please send me a ```raw``` file to test?
Everytime I can only generated a total black image, I cannot locate where's the problem, because I'm a new hand on image processing relative Python module.

**Comment by Elin24** [comment]
This is what you want, [scene.zip](https://github.com/gjy3035/GCC-CL/files/3572746/scene.zip)

**Comment by 2811299** [comment]
Thank you very mush, after download your ```draw``` file, I can display mask image using this code
>mask = np.fromfile(raw_file, 'uint8').reshape(1080, 1920) * 255
        mask = Image.fromarray(mask)
        mask.show()

But if I try to load the ```raw``` file generated myself, it will always be total black,

I installed all the mods you mentioned exactly, everything goes well except last step it asks me to press F5, nothing happened after I press F5, so I just restart the game myself.
Following are the files I generated myself, could you please help me to find out what's the matter with the file generated myself?
[gta-collect-data.zip](https://github.com/gjy3035/GCC-CL/files/3573297/gta-collect-data.zip)
[label-data.zip](https://github.com/gjy3035/GCC-CL/files/3573302/label-data.zip)

or could you please also send me your GCC-cl data from GTA5? So I'm able to check if it's the problem of my game or the GCC-label Python code my using.

**Comment by 2811299** [comment]
Oh, at last, I know the reason, MSAA should be turn off.
According to https://github.com/umautobots/GTAVisionExport/tree/master/managed
