### ISSUE TITLE
哪里可以下到现成的数据集

### ISSUE THREAD

**Issue by wenxingsen** [gjy3035/GCC-CL#15]

**Comment by Elin24** [comment]
You can download the GCC dataset from [https://mailnwpueducn-my.sharepoint.com/:f:/g/personal/gjy3035_mail_nwpu_edu_cn/Eo4L82dALJFDvUdy8rBm6B0BuQk6n5akJaN1WUF1BAeKUA?e=ge2cRg](https://mailnwpueducn-my.sharepoint.com/:f:/g/personal/gjy3035_mail_nwpu_edu_cn/Eo4L82dALJFDvUdy8rBm6B0BuQk6n5akJaN1WUF1BAeKUA?e=ge2cRg)
