### ISSUE TITLE
Where is SceneDirectorAnim.txt?

### ISSUE THREAD

**Issue by FutureShow** [gjy3035/GCC-CL#2]
In Script.cpp line 26, function "initAnimations " get "SceneDirectorAnim.txt". Unfortunately, I cannot find the txt file so that the function always returned False. Can you offer the file? Thanks!

**Comment by Elin24** [comment]
Please forgiven my negligence. I have  uploaded it in [**releases**](https://github.com/gjy3035/GCC-CL/releases) part.
 Thanks for your attention!

**Comment by FutureShow** [comment]
Thanks! : )
