### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by simuji** [gjy3035/GCC-CL#22]
因为nuget安装的minhook库无法使用，我用了GCC-CL-TOOLS里面的GCC-CL.asi,设置相机，多边形区域和四个相机还有设置人数范围都是正常的，但是重开游戏按L后，在生成人物时会显示GCC-CL.asi出错，请问是因为不能直接用GCC-CL.asi吗，另外，我没有安装No Chromatic aberration & Lens distortion 1.52，会对运行有影响吗

**Comment by simuji** [comment]
An exception occurred while executing 'GCC-CL.asi' (0x00007FFCC11BD890), id 33
这是scripthook.log里的出错报告

**Comment by Elin24** [comment]
1. minihook库安装应该是可以使用的，暂时bu清楚你使用了什么导致无法生成正确的asi；
2. No Chromatic aberration & Lens distortion 不安装不影响运行，但分割图和RGB图会有偏差；
3. GCC-CL的错误不太清楚，你的log没有具体贴出来，你要定位到log 的最后一行（你有放入zip里那个txt吗？——这个是我猜的）
