### ISSUE TITLE
Gives error when press 'L'

### ISSUE THREAD

**Issue by furkancoskun** [gjy3035/GCC-CL#24]
I can set camera and points but when I push 'L'. It crashes and gives the error:
> _CORE: An exception occurred while executing 'GCC-CL.asi...._

Id is different for different trials.

Here is my log:
[GCC-CL.log](https://github.com/gjy3035/GCC-CL/files/7777472/GCC-CL.log)

End of the log:
> [1640546796542] : finished keep camera...
[1640546812921] : data\part_1_3\eyeInfo.log
[1640546812922] : get eye info done.
[1640546812922] : -46.131100 461.612000 159.093002
[1640546812922] : -40.060200 0.000015 210.817993
[1640546812922] : 40.000000
[1640546813048] : finished keep camera...
[1640546822267] : end defineArea
[1640546850844] : now have = -1

I have read the [issue #5](https://github.com/gjy3035/GCC-CL/issues/5). My txt file is in the root folder and some files(part_ folders and .logs extension files) are created in my data folder.

What could be the cause of the error? Could you help me?

**Comment by Elin24** [comment]
Hi, can you show your fold structure of `data` ?

**Comment by Elin24** [comment]
BTW, have you tried this: directly press "L" to lunch it when you enter the game?

**Comment by furkancoskun** [comment]
Problem solved. It turns out that I didn't press F5 before 'L'. When I applied the procedure correctly, I could get results. 

Thanks for your good work and support!
