### ISSUE TITLE
script hook V error when generating people

### ISSUE THREAD

**Issue by duanzhiihao** [gjy3035/GCC-CL#5]
Hi, I have created and saved 1 scene by following your steps. I restart the game and press `L`, then my man falls from the sky to ground successfully. But then(like 3:44 in your youtube video) there comes an error window:
`SCRIPT HOOK V ERROR`
`CORE: An exception occurred while executing 'GCC-CL.asi' `
`(0x00007FFC0ED7D890), id43`
, and there are no people on the ground. I can do nothing but exit the game.

Could you tell me what's happening? If I want to debug it, which source file should I look at?

**Comment by yixinWang2018** [comment]
i have the same problem as you, and now have you found a solution?

**Comment by duanzhiihao** [comment]
> i have the same problem as you, and now have you found a solution?

Not yet

**Comment by yixinWang2018** [comment]
Maybe we can discuss it

**Comment by duanzhiihao** [comment]
> Maybe we can discuss it

ok, 我这周研究下, 有进展了发到这里

**Comment by yixinWang2018** [comment]
ok~

**Comment by Elin24** [comment]
After some exploration with a friend having this problem, this reason is there is no `SceneDirectorAnim.txt` in the game's root folder.

I have updated the `readme` file. Following below step could solve this problem:
> Download [GCC-COllector-Tool](https://github.com/gjy3035/GCC-CL/releases) and put `SceneDirectorAnim.txt` in the game's root folder.

deatailed infomation could be obtained from [issue 2](https://github.com/gjy3035/GCC-CL/issues/2)

**Comment by duanzhiihao** [comment]
I have put the `SceneDirectorAnim.txt` in the right place, but the problem remains. Can it be some problems with version change?

**Comment by leaicc** [comment]
> I have put the `SceneDirectorAnim.txt` in the right place, but the problem remains. Can it be some problems with version changes?

@Elin24 told me the following solution,you can have a try.Download DirectXTK.lib from [https://github.com/microsoft/DirectXTK?tdsourcetag=s_pctim_aiomsg](url) and recompile it，then put it in the folder C:\Users\gta5\Desktop\GCC-CL\GCC-Collector\deps\lib\，and next recompile GCC-Collector.sln

**Comment by yixinWang2018** [comment]
> @Elin24 told me the following solution,you can have a try.Download DirectXTK.lib from [https://github.com/microsoft/DirectXTK?tdsourcetag=s_pctim_aiomsg](url) and recompile it,then put it in the folder \GCC-CL\GCC-Collector\deps\lib,and next recompile GCC-Collector.sln

Have you solved it in this way?  i tried to recompile DirectXTK and repleace the old DirectXTK.lib in the fold, but the same problem is still exist after I pressing "L‘’. 
I also tried to use the compiled GCC-CL.asi of GCC-Collector-Tools, but failed.

**Comment by leaicc** [comment]
> > @Elin24 told me the following solution,you can have a try.Download DirectXTK.lib from [https://github.com/microsoft/DirectXTK?tdsourcetag=s_pctim_aiomsg](url) and recompile it,then put it in the folder \GCC-CL\GCC-Collector\deps\lib,and next recompile GCC-Collector.sln
> 
> Have you solved it in this way? i tried to recompile DirectXTK and repleace the old DirectXTK.lib in the fold, but the same problem is still exist after I pressing "L‘’.
> I also tried to use the compiled GCC-CL.asi of GCC-Collector-Tools but failed.

Yes,i solved the problem in this way,have you put SceneDirectorAnim.txt in the game's root folder?

**Comment by leaicc** [comment]
> > @Elin24 told me the following solution,you can have a try.Download DirectXTK.lib from [https://github.com/microsoft/DirectXTK?tdsourcetag=s_pctim_aiomsg](url) and recompile it,then put it in the folder \GCC-CL\GCC-Collector\deps\lib,and next recompile GCC-Collector.sln
> 
> Have you solved it in this way? i tried to recompile DirectXTK and repleace the old DirectXTK.lib in the fold, but the same problem is still exist after I pressing "L‘’.
> I also tried to use the compiled GCC-CL.asi of GCC-Collector-Tools but failed.

When you compiled DirectXTK.lib and GCC-Collector.sln,Did something go wrong?

**Comment by yixinWang2018** [comment]
> > > @Elin24 told me the following solution,you can have a try.Download DirectXTK.lib from [https://github.com/microsoft/DirectXTK?tdsourcetag=s_pctim_aiomsg](url) and recompile it,then put it in the folder \GCC-CL\GCC-Collector\deps\lib,and next recompile GCC-Collector.sln
> > 
> > 
> > Have you solved it in this way? i tried to recompile DirectXTK and repleace the old DirectXTK.lib in the fold, but the same problem is still exist after I pressing "L‘’.
> > I also tried to use the compiled GCC-CL.asi of GCC-Collector-Tools but failed.
> 
> When you compiled DirectXTK.lib and GCC-Collector.sln,Did something go wrong?

I have sent an email for you, looking forward for your reply.

**Comment by duanzhiihao** [comment]
> @Elin24 told me the following solution,you can have a try.Download DirectXTK.lib from [https://github.com/microsoft/DirectXTK?tdsourcetag=s_pctim_aiomsg](url) and recompile it,then put it in the folder \GCC-CL\GCC-Collector\deps\lib,and next recompile GCC-Collector.sln

That solution doesn't work for me too, the same error occurs after I fall on the ground.

By the way, after I select the number of people `F12 + 1`, it seems that nothing happens when I press `F5`. Can that be a problem?

My system is `win10, 64`, visual studio is `2017`, GCC-Collector is`x64 + release`, DirectXTK is `Desktop_2017_Win10 + x64 + release`, GTA V is the latest version on steam

**Comment by Elin24** [comment]
The build information like this:
![build information](https://s2.ax1x.com/2019/05/22/Vpwi5R.png)
If there are some problem about DirectXTK, please rebuild it through [microsoft-DirectXTK](https://github.com/microsoft/DirectXTK) and obtain a right release fitting your system, then replace corresponding lib file at `\GCC-CL\GCC-Collector\deps\lib`. Finally rebuild GCC-Collector.

If there are four log files in `part_XX_X`, 
1. areaInfo.log
2. eyeInfo.log
3. levelInfo.log
4. Zheight.log

the scene creator is fine.

Before press 'L', make sure `SceneDirectorAnim.txt` is in the game's root folder.

If there are still some problem when run it, open the 'GCC-CL.log' file in the game's root folder, and look for corresponding error place in `createCrowd.cpp` according to the last line in the log file.

**Comment by duanzhiihao** [comment]
Thank you for your tips. I tried your debugging method like the following:

1. I modify the `createCrowd.cpp` at `line 376`:
```
auto runSceneCreator = [&](int avg2) {
    int m = readImgNum();
    for (int i = nowHave; i < m; i++) {
        log_to_file("m = " + std::to_string(m));
	std::string weather = setTimeAndWeather();
	log_to_file("line 376");
	int pedNum = avg2 * 0.25 + rand() % int(avg2 * 0.75) + 1;
	log_to_file("line 378");
	createOneScene(281, mix, mxx - mix, miy, mxy - miy, weather, pedNum);
    }
};
```
2. Rebuild, copy to GTA V, fall from the sky, ERROR. The last part of `GCC-CL.log` is like:
```
[1558496187417] : finished keep camera...
[1558496187419] : start time: 1558496187
[1558496187419] : m = 5
[1558496187420] : selected hour in timeSeg[6]
[1558496188914] : hour = 20
[1558496190911] : hour = 20, CLEAR
[1558496190912] : line 376
```

It seems that the error occurs at line 376 of createCrowd.cpp: `int pedNum = avg2 * 0.25 + rand() % int(avg2 * 0.75) + 1;` I'm not familiar with C++, so could you give me some hint about it?

**Comment by MyronXie** [comment]
I have the same problems too...

Because I have problems building GCC-Collector using my own computer (maybe some config problems with Visual Studio...), so I used `GCC-CL.asi` and `SceneDirectorAnim.txt` in `GCC-Collector-Tools`.

I can see a man fall from sky and switch to the builded scene, and then the GTAV game crashed.

My `GCC_GL.log` is like
```
[1558506818266] : finished keep camera...
[1558506818269] : start time: 1558506818
[1558506818273] : m = 5
[1558506818302] : selected hour in timeSeg[0]
[1558506819197] : hour = 2
[1558506821213] : hour = 2, CLEAR
[1558506821219] : the pedestrian number of the scene: 7
[1558506821221] : average height = 70.396202
[1558506821224] : no anims : true
```
And error window msg:
```
SCRIPT HOOK V ERROR
CORE: An exception occurred while executing 'GCC-CL.asi' 
(0x00007FFC0ED7D890), id 33
```

So maybe I should try to build my own DirectXTK and GCC-Collector and then it does work? (:з」∠)

**Comment by leaicc** [comment]
> I have the same problems too...
> 
> Because I have problems building GCC-Collector using my own computer (maybe some config problems with Visual Studio...), so I used `GCC-CL.asi` and `SceneDirectorAnim.txt` in `GCC-Collector-Tools`.
> 
> I can see a man fall from sky and switch to the builded scene, and then the GTAV game crashed.
> 
> My `GCC_GL.log` is like
> 
> ```
> [1558506818266] : finished keep camera...
> [1558506818269] : start time: 1558506818
> [1558506818273] : m = 5
> [1558506818302] : selected hour in timeSeg[0]
> [1558506819197] : hour = 2
> [1558506821213] : hour = 2, CLEAR
> [1558506821219] : the pedestrian number of the scene: 7
> [1558506821221] : average height = 70.396202
> [1558506821224] : no anims : true
> ```
> 
> And error window msg:
> 
> ```
> SCRIPT HOOK V ERROR
> CORE: An exception occurred while executing 'GCC-CL.asi' 
> (0x00007FFC0ED7D890), id 33
> ```
> 
> So maybe I should try to build my own DirectXTK and GCC-Collector and then it does work? (:з」∠)

Put SceneDirectorAnim.txt in the game's root folder，then recompile DirectXTK.lib and  GCC-Collector.asi（x64 + release）

**Comment by Elin24** [comment]
if setting level = 1, the asi is gong to crash. This bug is in function `readLevelFile()` in `infoIO.cpp`, which has been solved.

If still having problem, please remind me.

Sorry for my late reply. @duanzhiihao

**Comment by duanzhiihao** [comment]
@Elin24 Thank you so much, I download your new `GCC-Collector` and everything is working.
By the way, after I press `L`, all I have to do is to wait, is that right? It seems that my man is falling from the sky again and again, and never ends.

**Comment by Elin24** [comment]
Yes, each time falling from sky means a time of scene or angle change. This will end when enough images have been created in each folder `data/part_XX_X`. 

As for the number of image, you can refer to the function `readImgNum()` in `ininfoIO.cpp`, we set 5 as default image number.

**Comment by 2811299** [comment]
Game crashed when I press 'L', after man dropping, it will crash, SceneDirectorAnim.txt in the game root folder, and recompiled DirectXTK
