### ISSUE TITLE
How to get binary mask of people

### ISSUE THREAD

**Issue by duanzhiihao** [gjy3035/GCC-CL#6]
Hi, in your project [website](https://gjy3035.github.io/GCC-CL/) you show a [binary mask](https://gjy3035.github.io/GCC-CL/images/example_mask_1.jpg) of people in addition to marks on people's head. How can we achieve that using GTA V?

**Comment by gjy3035** [comment]
Line 56 in https://github.com/gjy3035/GCC-CL/blob/master/GCC-Labeler/main.py produces the crowd 
mask in `.raw` files.

**Comment by duanzhiihao** [comment]
I directly run `main.py`, then read the `.raw` file:
```
raw_path = 'D:/Codes/gta5dataset/scene_1_0/segs/1558631488.raw'

seg = np.fromfile(raw_path, 'uint8')
seg = seg.reshape(1440, 2560)

plt.imshow(s,cmap='gray')
plt.show()
```
Then it shows like this
![image](https://user-images.githubusercontent.com/24869582/58437494-39865500-8098-11e9-8e84-3c5381dbd11a.png)
The corresponding `.png` image is
![image](https://user-images.githubusercontent.com/24869582/58437566-8833ef00-8098-11e9-9b9c-f319c831d2b4.png)

I also tried the `.raw` file in `GTA V/data/part_1_0/xxxxxxxx/part_0.raw`, it is the same as the above black&white one.
Could you tell me what it should be?
